export const FETCH_ROOMS_SUCCESS = "FETCH_ROOMS_SUCCESS";
export const FETCH_AVAILABLE_ROOMS_SUCCESS =
  "FETCH_AVAILABLE_ROOMS_SUCCESS";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILED = "CREATE_ORDER_FAILED";
export const FETCH_USER_ORDERS_SUCESS = "FETCH_USER_ORDERS_SUCESS";
export const FETCH_USER_ORDERS_FAILED = "FETCH_USER_ORDERS_FAILED";
export const CLEAR_ORDER_SUCCESS = "CLEAR_ORDER_SUCCESS";
export const VALIDATE_FORM_SUCCESS = "VALIDATE_FORM_SUCCESS";
export const VALIDATE_FORM_FAILED = "VALIDATE_FORM_FAILED";
export const USER_SIGNUP_SUCESS = "USER_SIGNUP_SUCESS";
export const USER_SIGNUP_FAILED = "USER_SIGNUP_FAILED";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAILED = "DELETE_ORDER_FAILED";
